In [1]:
from bs4 import BeautifulSoup
import numpy as np
import unicodedata

In [408]:
#Import html file containing hero server stats
#The file is from hotslogs.com

with open("hots_index.html") as fp:
    soup = BeautifulSoup(fp,'html.parser')

In [440]:
#Parse the table header
#Inspect HTML code + trial & error
header = []
for head in soup.find_all('th')[1:]:
    blah = head.text
    blah = str(blah)
    header.append(blah)
    if blah == 'XP':   #final entry
       break

In [410]:
#Check header read out
print(header)

['Hero', 'Games', 'Win %', 'Avg Length', 'T/D', 'Takedowns', 'Kills', 'Deaths', 'Hero Dmg', 'Siege Dmg', 'Healing', 'Self Heal', 'Dmg Taken', 'XP']


In [441]:
#Parse the table body (hero names and stats)
#90 heros and 14 parameters
stats_list = [[0 for j in range(14)] for i in range(90)] 
i=0
for row in soup.find_all('tr')[3:93]:
    j=0
    for col in row.find_all('td')[1:]:
        blah = col.text
        stats_list[i][j] = str(blah).replace("\xa0","0")
        j+=1
    i+=1

In [412]:
#Check first line
print(stats_list[0])

['Mephisto', '49,066', '52.3%', '00:18:43.9610000', '4.6', '13.5', '3.9', '2.9', '65,844', '92,011', '0', '4,463', '44,140', '11,605']


In [442]:
nrows = len(stats_list)
ncols = len(stats_list[0])

In [443]:
#Extract a list of hero names
heroes = []
for i in range(len(stats_list)):
    heroes.append(stats_list[i][0])

In [415]:
print(heroes)

['Mephisto', "Zul'jin", 'Valla', 'Orphea', 'Li-Ming', 'Hanzo', 'Junkrat', 'Cassia', 'Chromie', 'Tychus', "Gul'dan", 'Gall', 'Lunara', "Kael'thas", 'Tassadar', 'Azmodan', 'Fenix', 'Sgt. Hammer', 'Deathwing', 'Alarak', 'Zagara', 'Nazeebo', 'Tracer', 'Nova', 'Genji', 'Qhira', "Kel'Thuzad", 'Malthael', 'Jaina', 'Sylvanas', 'Raynor', 'Falstad', 'Hogger', 'Greymane', 'Gazlowe', 'Thrall', 'Maiev', 'Cho', 'Ragnaros', 'Probius', 'D.Va', 'Artanis', 'Medivh', 'Imperius', 'Leoric', 'Xul', 'Zarya', 'Kerrigan', 'Zeratul', 'Valeera', 'Samuro', 'Sonya', 'Blaze', 'Rexxar', 'Chen', 'Abathur', 'Arthas', 'Varian', 'Stitches', 'Illidan', 'Tyrael', 'Johanna', "Mal'Ganis", 'Yrel', 'Mei', 'The Butcher', 'Diablo', 'Tyrande', 'Muradin', 'Dehaka', "Anub'arak", 'Kharazim', 'The Lost Vikings', 'Garrosh', 'Murky', 'Li Li', 'Whitemane', 'Stukov', 'Auriel', 'Anduin', 'Lúcio', 'Malfurion', 'E.T.C.', 'Uther', 'Alexstrasza', 'Rehgar', 'Deckard', 'Ana', 'Brightwing', 'Lt. Morales']


In [444]:
#Convert time from h:m:s to minutes
#We probably won't use it but just in case
for i in range(nrows):
    h, m ,s = stats_list[i][3].split(':')
    stats_list[i][3] = str(round(float(h)*60 + float(m)+ float(s)/60,2))

In [417]:
stats_list[0][3].split(':')

['18.73']

In [418]:
stats_list[0]

['Mephisto',
 '49,066',
 '52.3%',
 '18.73',
 '4.6',
 '13.5',
 '3.9',
 '2.9',
 '65,844',
 '92,011',
 '0',
 '4,463',
 '44,140',
 '11,605']

In [445]:
#Numpify the stats
#Yes, it's a word
stats = np.zeros((nrows,ncols-1))
for i in range(nrows):
    for j in range(ncols-1):
        blah = stats_list[i][j+1].replace(" ","0").replace("'","").replace("%","").replace(",","")
        stats[i,j] = float(blah)

In [420]:
stats[0]

array([4.9066e+04, 5.2300e+01, 1.8730e+01, 4.6000e+00, 1.3500e+01,
       3.9000e+00, 2.9000e+00, 6.5844e+04, 9.2011e+04, 0.0000e+00,
       4.4630e+03, 4.4140e+04, 1.1605e+04])

In [76]:
np.savez('hots_stats.npz', header=header, heroes=heroes, stats=stats)

In [84]:
#Import html file containing hero internal stats (HP, damage...etc)
#The file is from hotsnerd.com
#We might use them with dim-red
with open("hotsnerd.html") as fp:
    soup2 = BeautifulSoup(fp,'html.parser')

In [282]:
#Parse the table
header = []
for head in soup2.find_all('td')[:]:
    blah = head.text
    blah = str(blah).replace("\n","").replace(" ","").replace("N/A","0").replace("\xa0",".")
    header.append(blah)
    if blah == 'XP': #I don't know why I kept this line.
       break

In [163]:
print(header[4::12])

['1.0', '1.5', '5.5', '6.5', '5.5', '1.5', '1.2', '2.0', '5.5', '5.5', '4.5', '5.5', '4.5', '2.0', '2.0', '7.0', '3.8', '5.5', '2.5', '1.5', '1.0', '1.2', '1.5', '5.5', '6.2', '5.0', '0', '1.2', '1.2', '4.5', '5.5', '1.2', '5.5', '6.5', '2.0', '1.2', '2.0', '5.5', '1.5', '5.5', '5.5', '5.5', '2.0', '1.8', '2.0', '5.5', '5.5', '5.5', '5.5', '5.5', '1.5', '1.3', '5.5', '1.5', '5.5', '4.5', '4.5', '1.0', '1.2', '5.5', '6.5', '5.5', '3.0', '2.2', '2.0', '6.5', '1.5', '5.5', '1.5', '2.0', '5.5', '11.0', '1.5', '1.5', '1.5', '5.5', '6.5', '1.5', '4.0', '6.5', '1.2', '1.5', '5.0', '4.5', '1.5', '6.0', '1.0', '1.2', '5.5', '1.2', '1.2', '1.2', '5.5', '1.5', '1.5', '6.6', '4.5', '1.5', '5.5']


In [394]:
heroes2 = np.array(header[0::12])#names
dps = header[1::12]#damage per second
rng = header[4::12]#attack range
hp = header[5::12]#hit point
blah = np.stack((dps,rng,hp))
stats2 = np.transpose(blah.astype(float))

In [395]:
print(heroes2.shape, stats2.shape)

(99,) (99, 3)


In [396]:
temp = [heroes2,stats2]

In [300]:
#Some heroes have multiple configuratios or consists of multiple characters
#We have to make choices on how to combine them into a single hero
heroes2 = temp[0]
stats2 = temp[1]

In [397]:
#D. Va: Use mech stats only
indx = np.argwhere(heroes2=="D.Va(Mech)")[0,0]
heroes2 = np.delete(heroes2, indx+1,axis=0)
stats2 = np.delete(stats2,indx+1,axis=0)
heroes2[indx]='D.Va'

In [398]:
#Fenix: Average
indx = np.argwhere(heroes2=="Fenix(PhaseBomb)")[0,0]
heroes2 = np.delete(heroes2, indx+1,axis=0)
stats2[indx] = (stats2[indx]+stats2[indx+1])/2
stats2 = np.delete(stats2,indx+1,axis=0)
heroes2[indx]='Fenix'

In [399]:
#Gall: Set to Cho
indx = np.argwhere(heroes2=="Gall")[0,0]
indx2 = np.argwhere(heroes2=="Cho")[0,0]
stats2[indx] = stats2[indx2]

In [400]:
#Greymane: Average
indx = np.argwhere(heroes2=="Greymane(Human)")[0,0]
heroes2 = np.delete(heroes2, indx+1,axis=0)
stats2[indx] = (stats2[indx]+stats2[indx+1])/2
stats2 = np.delete(stats2,indx+1,axis=0)
heroes2[indx]='Greymane'

In [401]:
#Rexxar: Add DPS and HP, average range
indx = np.argwhere(heroes2=="Rexxar")[0,0]
heroes2 = np.delete(heroes2, indx+1,axis=0)
stats2[indx,0::2] = (stats2[indx,0::2]+stats2[indx+1,0::2])
stats2[indx,1] = (stats2[indx,1]+stats2[indx+1,1])/2
stats2 = np.delete(stats2,indx+1,axis=0)

In [402]:
#Hammer: Average
indx = np.argwhere(heroes2=="Sgt.Hammer")[0,0]
heroes2 = np.delete(heroes2, indx+1,axis=0)
stats2[indx] = (stats2[indx]+stats2[indx+1])/2
stats2 = np.delete(stats2,indx+1,axis=0)
heroes2[indx]='Sgt. Hammer'

In [403]:
#Vikings: Add DPS and HP, average range
indx = np.argwhere(heroes2=="TheLostVikings(Baleog)")[0,0]
heroes2 = np.delete(heroes2, indx+1,axis=0)
heroes2 = np.delete(heroes2, indx+1,axis=0)
stats2[indx,0::2] = (stats2[indx,0::2]+stats2[indx+1,0::2]+stats2[indx+2,0::2])
stats2[indx,1] = (stats2[indx,1]+stats2[indx+1,1]+stats2[indx+2,1])/3
stats2 = np.delete(stats2,indx+1,axis=0)
stats2 = np.delete(stats2,indx+1,axis=0)
heroes2[indx]='The Lost Vikings'

In [404]:
#Varian: Average
indx = np.argwhere(heroes2=="Varian(ColossusSmash)")[0,0]
heroes2 = np.delete(heroes2, indx+1,axis=0)
heroes2 = np.delete(heroes2, indx+1,axis=0)
stats2[indx] = (stats2[indx]+stats2[indx+1]+stats2[indx+2])/3
stats2 = np.delete(stats2,indx+1,axis=0)
stats2 = np.delete(stats2,indx+1,axis=0)
heroes2[indx]='Varian'

In [406]:
#ETC and Rehgar: remove extra value listed from earlier oatch
indx = np.argwhere(heroes2=="E.T.C.")[0,0]
stats2[indx,2]=np.round(stats2[indx,2])
                        
indx = np.argwhere(heroes2=="Rehgar")[0,0]
stats2[indx,2]=np.round(stats2[indx,2])

In [424]:
stats2sorted = stats2[np.argsort(heroes)]


In [448]:
stats = np.concatenate((stats,stats2sorted), axis=1)

In [446]:
header.extend(['DPS','Range','HP'])

In [447]:
header

['Hero',
 'Games',
 'Win %',
 'Avg Length',
 'T/D',
 'Takedowns',
 'Kills',
 'Deaths',
 'Hero Dmg',
 'Siege Dmg',
 'Healing',
 'Self Heal',
 'Dmg Taken',
 'XP',
 'DPS',
 'Range',
 'HP']

In [449]:
np.savez('hots_stats_ext.npz', header=header, heroes=heroes, stats=stats)

In [407]:
np.concatenate((np.transpose(heroes2[np.newaxis]),stats2),axis=1)

array([['Abathur', '55.1', '1.0', '1014.0'],
       ['Alarak', '266.5', '1.5', '2888.0'],
       ['Alexstrasza', '108.1', '5.5', '2514.0'],
       ['Ana', '58.9', '6.5', '2366.0'],
       ['Anduin', '125.9', '5.5', '2466.0'],
       ["Anub'arak", '119.9', '1.5', '3185.0'],
       ['Artanis', '163.9', '1.2', '3740.0'],
       ['Arthas', '140.7', '2.0', '4236.0'],
       ['Auriel', '118.5', '5.5', '2518.0'],
       ['Azmodan', '125.4', '5.5', '3649.0'],
       ['Blaze', '81.4', '4.5', '4295.0'],
       ['Brightwing', '133.1', '5.5', '2111.0'],
       ['Cassia', '197.2', '4.5', '2459.0'],
       ['Chen', '148.0', '2.0', '3662.0'],
       ['Cho', '183.6', '2.0', '4578.0'],
       ['Chromie', '121.4', '7.0', '2059.0'],
       ['D.Va', '130.4', '3.8', '3110.0'],
       ['Deathwing', '153.8', '2.5', '4073.0'],
       ['Deckard', '84.9', '1.5', '2637.0'],
       ['Dehaka', '175.9', '1.0', '3532.0'],
       ['Diablo', '147.5', '1.2', '4184.0'],
       ['E.T.C.', '183.3', '1.5', '3333.0'],
     

In [374]:
print(stats2.shape,np.transpose(heroes2[np.newaxis]).shape)

(90, 3) (90, 1)


In [349]:
heroes2

array(['Abathur', 'Alarak', 'Alexstrasza', 'Ana', 'Anduin', "Anub'arak",
       'Artanis', 'Arthas', 'Auriel', 'Azmodan', 'Blaze', 'Brightwing',
       'Cassia', 'Chen', 'Cho', 'Chromie', 'D.Va', 'Deathwing', 'Deckard',
       'Dehaka', 'Diablo', 'E.T.C.', 'Falstad', 'Fenix', 'Gall',
       'Garrosh', 'Gazlowe', 'Genji', 'Greymane', "Gul'dan", 'Hanzo',
       'Hogger', 'Illidan', 'Imperius', 'Jaina', 'Johanna', 'Junkrat',
       "Kael'thas", "Kel'Thuzad", 'Kerrigan', 'Kharazim', 'Leoric',
       'LiLi', 'Li-Ming', 'Lt.Morales', 'Lucio', 'Lunara', 'Maiev',
       "Mal'Ganis", 'Malfurion', 'Malthael', 'Medivh', 'Mei', 'Mephisto',
       'Muradin', 'Murky', 'Nazeebo', 'Nova', 'Orphea', 'Probius',
       'Qhira', 'Ragnaros', 'Raynor', 'Rehgar', 'Rexxar', 'Samuro',
       'Sgt. Hammer', 'Sonya', 'Stitches', 'Stukov', 'Sylvanas',
       'Tassadar', 'TheButcher', 'The Lost Vikings', 'Thrall', 'Tracer',
       'Tychus', 'Tyrael', 'Tyrande', 'Uther', 'Valeera', 'Valla',
       'Varian', 'Whitem

In [267]:
blah = stats2

In [270]:
blah[0]=np.array([1,2,3])

In [271]:
blah

array([[1.0000000e+00, 2.0000000e+00, 3.0000000e+00],
       [2.6650000e+02, 1.5000000e+00, 2.8880000e+03],
       [1.0810000e+02, 5.5000000e+00, 2.5140000e+03],
       [5.8900000e+01, 6.5000000e+00, 2.3660000e+03],
       [1.2590000e+02, 5.5000000e+00, 2.4660000e+03],
       [1.1990000e+02, 1.5000000e+00, 3.1850000e+03],
       [1.6390000e+02, 1.2000000e+00, 3.7400000e+03],
       [1.4070000e+02, 2.0000000e+00, 4.2360000e+03],
       [1.1850000e+02, 5.5000000e+00, 2.5180000e+03],
       [1.2540000e+02, 5.5000000e+00, 3.6490000e+03],
       [8.1400000e+01, 4.5000000e+00, 4.2950000e+03],
       [1.3310000e+02, 5.5000000e+00, 2.1110000e+03],
       [1.9720000e+02, 4.5000000e+00, 2.4590000e+03],
       [1.4800000e+02, 2.0000000e+00, 3.6620000e+03],
       [1.8360000e+02, 2.0000000e+00, 4.5780000e+03],
       [1.2140000e+02, 7.0000000e+00, 2.0590000e+03],
       [1.3040000e+02, 3.8000000e+00, 3.1100000e+03],
       [1.5380000e+02, 2.5000000e+00, 4.0730000e+03],
       [8.4900000e+01, 1.500

In [377]:
A = np.arange(3)

In [389]:
A[0:3:2]=np.array([4,5])
print(A)

[4 1 5]


In [390]:
A[0:1]

array([4])